openapi: 3.0.0
info:
  title: Payments API
  description: API para gestionar pagos con tarjetas de crédito.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Servidor local

paths:
  /payments:
    get:
      summary: Listado de todos los pagos
      operationId: getPayments
      tags:
        - Payments
      responses:
        '200':
          description: Lista de pagos existente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PaymentResponse'
        '500':
          description: Error interno del servidor
    post:
      summary: Registrar un nuevo pago
      operationId: createPayment
      tags:
        - Payments
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRequest'
      responses:
        '201':
          description: Pago creado exitosamente
        '400':
          description: Solicitud inválida
        '500':
          description: Error interno del servidor

components:
  schemas:
    PaymentRequest:
      type: object
      properties:
        cardNumber:
          type: string
          description: Número de la tarjeta de crédito (16-19 dígitos)
        amount:
          type: number
          format: double
          description: Monto del pago
        paymentDate:
          type: string
          format: date
          description: Fecha del pago (YYYY-MM-DD)
        description:
          type: string
          description: Descripción opcional del pago
      required:
        - cardNumber
        - amount
        - paymentDate

    PaymentResponse:
      type: object
      properties:
        id:
          type: integer
          description: Identificador único del pago
        cardNumber:
          type: string
          description: Número de tarjeta enmascarado
        amount:
          type: number
          format: double
          description: Monto del pago
        paymentDate:
          type: string
          format: date
          description: Fecha del pago (YYYY-MM-DD)
        description:
          type: string
          description: Descripción opcional del pago
        createdAt:
          type: string
          format: date
          description: Fecha en que se creó el registro
